name: Terraform Docs ðŸ“œ

on:
  push:
    branches-ignore: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Exit with error if terraform-docs has changed the README.md
      run: |
        make docs
        git diff --exit-code README.md
        if [ $? -eq 0 ]; then
          echo "README.md is up to date"
        else
          echo "README.md is out of date. Please run 'make docs' and commit the changes."
          exit 1
        fi